// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsP4gN8epKciiy9q6OkkYscgomBxG4bJg',
    appId: '1:412733276283:web:90f9a9adc9b73daccda2de',
    messagingSenderId: '412733276283',
    projectId: 'bandi-official',
    authDomain: 'bandi-official.firebaseapp.com',
    storageBucket: 'bandi-official.appspot.com',
    measurementId: 'G-E970GPLY2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTwTZJwx5MrScyniZSiYo5BONNOQV2sEI',
    appId: '1:412733276283:android:9c5dc513bc3659cfcda2de',
    messagingSenderId: '412733276283',
    projectId: 'bandi-official',
    storageBucket: 'bandi-official.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBPbpIQbGmZbVx5jdQ730haEJoVbw6Mew',
    appId: '1:412733276283:ios:7c522acc7737aee4cda2de',
    messagingSenderId: '412733276283',
    projectId: 'bandi-official',
    storageBucket: 'bandi-official.appspot.com',
    iosBundleId: 'com.example.bandiOfficial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBPbpIQbGmZbVx5jdQ730haEJoVbw6Mew',
    appId: '1:412733276283:ios:7c522acc7737aee4cda2de',
    messagingSenderId: '412733276283',
    projectId: 'bandi-official',
    storageBucket: 'bandi-official.appspot.com',
    iosBundleId: 'com.example.bandiOfficial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsP4gN8epKciiy9q6OkkYscgomBxG4bJg',
    appId: '1:412733276283:web:26f12a8584c46ab0cda2de',
    messagingSenderId: '412733276283',
    projectId: 'bandi-official',
    authDomain: 'bandi-official.firebaseapp.com',
    storageBucket: 'bandi-official.appspot.com',
    measurementId: 'G-TE980YQF3J',
  );
}
